FROM ghcr.io/cyber-dojo-languages/bash:9a88d8f
LABEL maintainer=jon@jaggersoft.com

RUN \
apk add git && \
git clone https://github.com/bats-core/bats-core.git && \
cd bats-core && \
./install.sh /usr/local && \
apk del git

COPY red_amber_green.rb /usr/local/bin
