FROM ghcr.io/cyber-dojo-languages/bash:869fdc6
LABEL maintainer=jon@jaggersoft.com

RUN \
apk add git && \
git clone https://github.com/bats-core/bats-core.git && \
cd bats-core && \
./install.sh /usr/local && \
apk del git
